### ISSUE TITLE
Error in nginx: 504 Gateway Time-out

### ISSUE THREAD

**Issue by samithaf** [parris/private-npm-registry#2]
Hi,
I was able to enable sub filter. However when I try to run npm install with large dependancy set seems like nginx crashes. But when i install one package each time it works. OS is OSX

Error in nginx: 504 Gateway Time-out

**Comment by parris** [comment]
I'm not sure what is wrong specifically. I do however, at this point, recommend avoiding nginx and just using kappa with multiple mirrors. That or just creating a tarball of the completed install. In practice, nginx worked for a while, but then fell apart on us a year later for whatever reason. 

Here is a list of mirrors: http://blog.modulus.io/npm-mirrors

We use: 
- http://registry.npmjs.org
- http://npm.strongloop.com
- https://registry.nodejitsu.com

Kappa and reggie still seem to work for us although reggie is now deprecated technically. Another project to look at would be: https://www.npmjs.com/package/sinopia which handles both a private npm registry and mirroring in 1 package. This all being said, you should really figure out a way to create tarballs. Nothing is faster than not having to install dependencies at all.

**Comment by samithaf** [comment]
@parris I was almost successful with Sinopia. However it was having issue with node version that I am using which is 0.10.36. Sinopia works well with node version 0.12.0. However the my project dependencies are not compatible with node 0.12.0.

**Comment by samithaf** [comment]
Upgraded to latest node and switched to https://github.com/verdaccio/verdaccio
